appName: molly-mysql-canal

mysql:
  addr: 192.168.0.188:3306
  username: canal
  password: canal
  serverId: 99

redis:
  addrs:
    - 192.168.0.188:6379
  db: 5


rules:

  # 同步全局配置
  - mysql_sys_config_to_redis:
      tableRegex: nicole_robin_pro.sys_config\b
      initData: true
      clearBeforeData: true
      customPKColumn: config_key
      includeColumnNames:
        - config_value
      #serializationFormat: msgpack
      fieldNameFormat: lowerCamelCase
      syncTarget: redis
      redisRule:
        keyName: sys_config
        keyType: hash
